env:
  global:
    - secure: U5z8V2+wG3/ZB0YwSDxdOjzbLjlklJ1JaIw2T4f+n90BAEB9YiUdQbe7lAd3BQ6Lt/r1+mr7jQyK246aHHekPbD9wXYxhqA+e11yHg/Vvs+Hmzep9pqtEqjboMbApEXXesdgATs8qR+WKl5jNAv3WSVUDXtOWMfl9rt/Q7NAJZVRWMc/G94EsVWSm8fqPCJ2L9ly8fK28v8yLz1yUxuKCR8ypRGZ3Dh3cVuVk5wsNN17u+g4yCCcFZGgrpoKw5WDJcHTuyOnEUHBcZT7mvnG9rl6Kgz5rsIqglnBGrdsMpp2Nvvgjjmxg/hD4um/khg3h4T2pnQEoLmi/khxSRr8MlhDmSNRTvrQsMgpmFNkRAnC7c3iLqOGzWUdiU5jQ8BBWlEvpzS5DK/VIsc7SWY7W5MlL9eunNu01/VTF4s75V1yJpVCZr42MwcraH9v54MtzVsYo9FrBIg2LowUwxe5Zc9mfMYrjb7OOOtPk3uvMwCgnA5C/H4IltDON0puk8WNn6O3hrlL7wH1TIQB8ZWLYpU/RmGIRtwKmSeD7MhayAqSS5/lbB//0GUW3CIGJOFDK1ci3epuHOGEbK8dhASu2tbtL0FwRmiAPygdeFpSRJ9qt4hV4s85KiEHqwRd1CDymUkmNtzrweZ2G+0RW/H0ySnE/+43cbKmoT0VVkztRNA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Global-Advert-Servers-Blocklist---Personal-Edition
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
