env:
  global:
    - secure: VsP+4eEXWwoHhYiAcPI/gEokH6ARUgyKiUso4l1pOeiX7xBd83ml3nh/ghbROKJAclVb3iQZwOGOseIQeljQ4AYvyGaOgP0SbMygvcQepaTs8tNmxAs3WiasT0B0bDj9gxuIm1IMVRyQDvNavkTDpZr3fhdmXI56nisGAS7mGSMXphAK+/RAj1Fc+tOJCUyr3/P2YS62kiJC+CQ3wKEa1TYeb2+ODMRr2Y9r71iNlX9HKUfpwwnCXo5b04BZJ3RM9FVNd4trVVEF2uYWY6c/PkqGVRRAtJkuBo56Ws7ATbirbeYeHBxffSbNrXxMa74NfPB0PHwv4zBpH2rSPeL2s8jVUs6YSW+Cqd80UD7hka5yQHCYjoRzh0yI+OQpN7wM33f9cnxUEIXqzvQs7I1EpVt4XwkmhPVcr0f6yJEp9k6JozqCMXf9ixoJ2GRdKSkkXQu/cVZHwAnVYDA9rGwwAjmrjA+scCzY95jMxCwtK5irlNf3O9w9xviHiSVBBpeyEgFhRgdEdbiV36uRKsy0SJ+Z7FTSgaXI1f0N+2/Zm6TqtzE4r8RPKwh2JZdlJ2EgQqxIKKbtYtIOQ8b8nVVOmRvsPOAvXG9ycLUoA52vNrwFJjE2w1paxJUbGkJUtKu9eWfqwQvBwPwKt7+7Qe29TmAr9HQ3R724BOzxwCDc2TM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Global-Advert-Servers-Blocklist---Personal-Edition
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
